### ISSUE TITLE
Plugin support via gradle

### ISSUE THREAD

**Issue by nikolaievs** [pact-foundation/pact-plugins#19]
Hello,
I'm looking for a possibility to download protobuf plugin using gradle, so then `usePlugin("protobuf")` won't search on the local machine for the plugin. Is there is a solution for this?
Best regards

**Comment by rholshausen** [comment]
I'm just trying to understand your requirements. We can create a Gradle task that will download and install the protobuf plugin, but it will install it to the local machine where `usePlugin` will look for it. Is this what you are asking, or are you asking if there is a way to use it without installing it on the local machine?

**Comment by NikolaievSerhii** [comment]
Well, both options actually interesting.
But, the main point is to have something similar to `protobuf` plugin where you can define which protoc to use, so you don't need to install it manually.
So, the goal here - is that I will be able to clone the repo then just run `./gradlew clean build`, and the build pass successfully without any other steps to do.

**Comment by rholshausen** [comment]
Pact-JVM 4.6.0 can now auto-install known plugins

**Comment by YOU54F** [comment]
Pact-JVM and Pact-Rust (and in turn users of it via the Pact FFI), now have the ability to auto download required plugins.

Outside of that, the pact-plugin-cli is available to install plugins manually.

We do not have plans for officially create a maven, or gradle plugin. 

That being said, there is nothing stopping anyone in the community taking the time to create a maven or gradle plugin, to install Pact plugins.

You may wish to build it standalone, or integrate it into the Pact JVM project. 

Closing due to this being a feature we don't plan on delivering
