### ISSUE TITLE
Question: Is there a maven plugin to install plugin?

### ISSUE THREAD

**Issue by noorul** [pact-foundation/pact-plugins#26]
For a pure java project installing the plugin using pact-plugin-cli is an additional step. Is there a maven plugin that can help install the plugin?

**Comment by rholshausen** [comment]
There is no Maven plugin, but the work to support #19 will allow the plugins to be automatically installed when needed

**Comment by noorul** [comment]
Looks like #19 is for gradle.

**Comment by rholshausen** [comment]
https://github.com/pact-foundation/pact-plugins/issues/19 is independent of the build tool used.

**Comment by YOU54F** [comment]
Pact-JVM and Pact-Rust (and in turn users of it via the Pact FFI), now have the ability to auto download required plugins.

Outside of that, the pact-plugin-cli is available to install plugins manually.

We do not have plans for officially create a maven, or gradle plugin. 

That being said, there is nothing stopping anyone in the community taking the time to create a maven or gradle plugin, to install Pact plugins.

You may wish to build it standalone, or integrate it into the Pact JVM project. 

Closing due to this being a feature we don't plan on delivering
