### ISSUE TITLE
startMockServer doesn't set hostInterface, port, and tls in request

### ISSUE THREAD

**Issue by jojoxhsieh** [pact-foundation/pact-plugins#9]
Hi, I started to use this plugin framework recently.
However, I got an issue and it can't work properly in my environment.
I tried to run UT and generate pact file in docker with pact-protobuf-plugin.
But I always get this exception:

io.pact.plugins.jvm.core.PactPluginMockServerErrorException: Plugin protobuf failed to start a mock server: Failed to start gRPC mock server: Address not available (os error 99)

I tried to troubleshoot a bit, and it's because the pact-protobuf-plugin want to start a local mock server, but the target "[::1]:0" is not allowed in my docker container.
And I set hotInterface and port by MockServerConfig annotation, but it's not working.
Because io.pact.plugins.jvm.core.DefaultPluginManager#startMockServer doesn't really pass the config to plugin.
I am this sure this behavior is on purpose or a bug, could you please help to take a look?
Thank you.

**Comment by rmartine-ias** [comment]
Running into this issue as well. Our build system runs tests in a docker container; this is an issue getting in the way of using the pact-protobuf-plugin.

Steps to reproduce:
```bash
git clone https://github.com/pact-foundation/pact-plugins
cd pact-plugins/
docker run -it -v "$PWD:/mnt" -w /mnt debian:latest

# In container:

## Install Java
apt update
apt install -y openjdk-11-jre
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64/

## Install protobuf plugin
apt install -y wget
mkdir -p ~/.pact/plugins/protobuf-0.1.16
wget https://github.com/pactflow/pact-protobuf-plugin/releases/download/v-0.1.16/pact-plugin.json -O ~/.pact/plugins/protobuf-0.1.16/pact-plugin.json

### AMD64
# wget https://github.com/pactflow/pact-protobuf-plugin/releases/download/v-0.1.16/pact-protobuf-plugin-linux-x86_64.gz -O ~/.pact/plugins/protobuf-0.1.16/pact-protobuf-plugin.gz
### ARM64
wget https://github.com/pactflow/pact-protobuf-plugin/releases/download/v-0.1.16/pact-protobuf-plugin-linux-aarch64.gz -O ~/.pact/plugins/protobuf-0.1.16/pact-protobuf-plugin.gz

gunzip -N ~/.pact/plugins/protobuf-0.1.16/pact-protobuf-plugin.gz
chmod +x ~/.pact/plugins/protobuf-0.1.16/pact-protobuf-plugin

## Execute test
cd examples/gRPC/area_calculator/consumer-jvm/
./gradlew test --debug

# 2022-11-16T21:00:02.543+0000 [DEBUG] [TestEventLogger]     io.pact.plugins.jvm.core.PactPluginMockServerErrorException: Plugin protobuf failed to start a mock server: Failed to start gRPC mock server: Cannot assign requested address (os error 99)
# 2022-11-16T21:00:03.142+0000 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 10s
```

Setting `hostInterface = "127.0.0.1"`  on line 79 of `PactConsumerTest.java` (arg to `@MockServerConfig`) yields the same error.

Modifying [this line](https://github.com/pactflow/pact-protobuf-plugin/blob/1fea4f43d1fb70482e823d91d7dc35efba8b8656/src/mock_server.rs#L129) in pact-protobuf-plugin to be `127.0.0.1`, and the same for [this line](https://github.com/pact-foundation/pact-plugins/blob/ef0289fe14e3a1dcadc6e645357457e5f894f336/examples/gRPC/area_calculator/consumer-jvm/src/test/java/io/pact/example/grpc/consumer/PactConsumerTest.java#L81) in `PactConsumerTest` makes the tests succeed.

So I am pretty sure that @jojoxhsieh is right, that the config isn't passed to the plugin, because very manually setting the host (via recompiling the plugin) makes the tests pass, but setting `hostInterface` doesn't.

**Comment by YOU54F** [comment]
Great bug report!
